variables:
    CONAN_USERNAME: "user"
    CONAN_REFERENCE: "boost/1.69"
    CONAN_CHANNEL: "channel"
    CONAN_LOGIN_USERNAME: "user"
    
    CXX_STANDARD: "14"
    CXX_FLAGS: "-O3 -fopenmp -fvisibility=hidden -fmessage-length=0"
    Python_INCLUDE_DIR: "/opt/pyenv/versions/3.7.1/include/python3.7m"
    Python_LIBRARY_RELEASE: "/opt/pyenv/versions/3.7.1/lib/libpython3.7m.so"
    Python_EXECUTABLE: "/opt/pyenv/versions/3.7.1/bin/python"

.build-template: &build-template
    before_script:
        - sudo pip install --upgrade conan_package_tools
        - conan user
    script:
        - python build.py

gcc-4.9:
    image: conanio/gcc49
    variables:
        CONAN_GCC_VERSIONS: "4.9"
    <<: *build-template

gcc-5:
    image: conanio/gcc5
    variables:
        CONAN_GCC_VERSIONS: "5"
    <<: *build-template

gcc-6:
    image: conanio/gcc6
    variables:
        CONAN_GCC_VERSIONS: "6"
    <<: *build-template

gcc-7:
    image: conanio/gcc7
    variables:
        CONAN_GCC_VERSIONS: "7"
    <<: *build-template

gcc-8:
    image: conanio/gcc8
    variables:
        CONAN_GCC_VERSIONS: "8"
    <<: *build-template