
env:
   global:
     - CONAN_REFERENCE: "boost/1.69"
     - CONAN_USERNAME: "user"
     - CONAN_LOGIN_USERNAME: "user"
     - CONAN_CHANNEL: "channel"
     
     - CXX_STANDARD: "14"
     - CXX_FLAGS: "-O3 -fopenmp -fvisibility=hidden -fmessage-length=0"
     - Python_INCLUDE_DIR: "/opt/pyenv/versions/3.7.1/include/python3.7m"
     - Python_LIBRARY_RELEASE: "/opt/pyenv/versions/3.7.1/lib/libpython3.7m.so"
     - Python_EXECUTABLE: "/opt/pyenv/versions/3.7.1/bin/python"

linux: &linux
   os: linux
   dist: xenial
   sudo: required
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=conanio/gcc49

      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7

      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=conanio/clang39

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=conanio/clang40

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang70

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
